### ISSUE TITLE
Add a `--threshold-scale` parameter

### ISSUE THREAD

**Issue by apcamargo** [jolespin/pykofamsearch#1]
In `kofam_scan`, the `--threshold-scale` can be used to control the stringency of annotation. It simply [multiplies the bitscore cutoff by a constant](https://github.com/takaram/kofam_scan/blob/62cee3943aa28b96f498150f5e0bb2d7c498e648/lib/kofam_scan/result/with_threshold_scale_and_evalue_threshold/hit.rb#L26).

This could be an useful feature to have in `pykofamsearch`.

**Comment by jolespin** [comment]
Awesome. Thanks for adding this scaling threshold.   Did you catch any other thresholding features in the kofamscan code that isn't implemented here?

**Comment by apcamargo** [comment]
Not on the top of my head. I can think of a few extra features that could be useful (e.g. a command to automatically download and build a database, include module and pathway information in the output), but nothing really crucial. Replacing pandas with polars might bring a small performance improvement too.
